site_name: BoolForge
site_url: https://ckadelka.github.io/BoolForge
repo_name: ckadelka/BoolForge
repo_url: https://github.com/ckadelka/BoolForge

nav:
  - Home: index.md
  - Installation: install.md
  - Documentation:
    - "Boolean Function": documentation/boolean_function.md
    - "Boolean Network": documentation/boolean_network.md
    - "Wiring Diagram": documentation/wiring_diagram.md
    - Generate: documentation/generate.md
    - "Bio Models": documentation/bio_models.md
    - Utils: documentation/utils.md
  - Tutorials:
    - tutorials/tutorial01.ipynb
    - tutorials/tutorial02.ipynb
    - tutorials/tutorial03.ipynb
    - tutorials/tutorial04.ipynb
    - tutorials/tutorial05.ipynb
    - tutorials/tutorial06.ipynb
    - tutorials/tutorial07.ipynb
    - tutorials/tutorial08.ipynb

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: false
  - mkdocstrings:
      handlers:
        python:
          paths: [boolforge]
          options:
            show_source: false
            show_root_heading: true
            show_object_full_path: false
            docstring_style: sphinx
            merge_init_into_class: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js